App.template.action_bar.buttons = _.template([
  '<div class="col-md-12">',
  ' <div class="btn-group btn-group-xs">',
  '   <button type="button" class="btn btn-default" data-type="add">',
  '     <span class="glyphicon glyphicon-plus"></span>',
  '   </button>',
  ' </div>',
  ' <div class="btn-group btn-group-xs">',
  '   <button type="button" class="btn btn-default" data-type="up">',
  '     <span class="glyphicon glyphicon-circle-arrow-up"></span> ',
  '   </button>',
  '   <button type="button" class="btn btn-default" data-type="down">',
  '     <span class="glyphicon glyphicon-circle-arrow-down"></span> ',
  '   </button>',
  ' </div>',
  ' <div class="btn-group btn-group-xs">',
  '   <button type="button" class="btn btn-default" data-type="edit">',
  '     <span class="glyphicon glyphicon-pencil"></span> ',
  '   </button>',
  '   <button type="button" class="btn btn-success" data-type="save" style="display: none;">',
  '     <span class="glyphicon glyphicon-ok"></span> ',
  '   </button>',
  '   <button type="button" class="btn btn-default" data-type="lock">',
  '     <span class="glyphicon glyphicon-lock"></span> ',
  '   </button>',
  '   <button type="button" class="btn btn-default" data-type="remove">',
  '     <span class="glyphicon glyphicon-trash"></span> ',
  '   </button>',
  ' </div>',
  ' <div class="btn-group btn-group-xs">',
  '   <button type="button" class="btn btn-default" data-type="user">',
  '     <span class="glyphicon glyphicon-user"></span>',
  '   </button>',
  '   <button type="button" class="btn btn-default" data-type="time">',
  '     <span class="glyphicon glyphicon-time"></span>',
  '   </button>',
  '   <button type="button" class="btn btn-default" data-type="history">',
  '     <span class="glyphicon glyphicon-th-list"></span>',
  '   </button>',
  ' </div>',
  '</div>'
].join(''));